use_frameworks!

platform :ios, '10.0'

target 'MFSugarGrammar_Example' do
  
  pod 'MFSugarGrammar', :path => '../'
  
  pod 'Masonry'
  pod 'SDAutoLayout'

  target 'MFSugarGrammar_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
